### ISSUE TITLE
UB 3.0

### ISSUE THREAD

**Issue by planginc** [TomFrankly/pipedream-notion-voice-tasks#17]
Hi Frank,

I’m trying to set up the v3.0 workflow, but I’ve run into an issue. My Pipedream step shows "notion_voice_tasks" instead of "Parse and Create Tasks", as it does in your video. I’ve tried several approaches to resolve this, but I’m still not seeing the same things you’re demonstrating.

Here’s what I’ve tried so far:

Deleted my existing Pipedream workflow and reloaded it multiple times using the pipedream link you had:

- In your Android Workflow Tasker Setup youtube video.
- In the Pipedream Workflow tutorial youtube video.
- From the instructions on [ThomasFrank.com](https://thomasfrank.com/), specifically where it mentions using the workflow to get the "Parse and Create Tasks" feature.

I've followed along via the video and via the written instructions to try to get this to work but no luck.  I am not seeing what you're showing in the videos or the written instructions. 

I’ve been using your Voice-to-Text feature in Pipedream/Notion for a couple of years now (DAILY - it's awesome, tyty!) and am super excited to get this new version working, but I can’t figure out what I might be doing wrong.

Any guidance would be greatly appreciated!

Thanks so much,
-Pam

**Comment by planginc** [comment]
I did android/tasker if that matters.  the tast does make it from my phone to pipedream - it's the notion steps that aren't synced w/your video.

**Comment by TomFrankly** [comment]
Hi @planginc,

Since I shot that video, I updated the name of the workflow. Are you finding that you're unable to set up that Notion Voice Tasks action? Do you hit any errors?

**Comment by planginc** [comment]
Hi @TomFrankly - tysm for getting back to me!!!   

Yes, I'm hitting errors: https://www.loom.com/share/2d9f3a35a4684caa885f829a472fa42c

In case it's hard to see in the video:

Cannot read properties of undefined (reading 'length')
    at Object.checkBody (file:///tmp/__pdg__/dist/code/345635712611569e7f72e17f38acdd33fba5d281d8e52da3a3e6c270391b35f3/component.mjs:307:681)
    at Object.run (file:///tmp/__pdg__/dist/code/345635712611569e7f72e17f38acdd33fba5d281d8e52da3a3e6c270391b35f3/component.mjs:335:1160)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.executeComponent (/var/task/launch_worker.js:292:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:792:28)

**Comment by TomFrankly** [comment]
@planginc gotcha – looks like there is indeed a bug. I'll try to fix it when I have some time!

**Comment by planginc** [comment]
ty ty!!
