### ISSUE TITLE
Error on pipedream test

### ISSUE THREAD

**Issue by jkendric** [TomFrankly/pipedream-notion-voice-tasks#2]
I have followed you tutroial and unfortuantely am stuck at the testing portion of pipedream.  I get the follwing error:

Error
SyntaxError: The requested module 'openai' does not provide an export named 'Configuration'

DETAILS
Error: SyntaxError: The requested module 'openai' does not provide an export named 'Configuration'
    at handleError (/var/task/common.js:38:40)
    at Runner.runUserCode (file:///var/task/lambda_handler.mjs:866:9)
    at async Runner.run (file:///var/task/lambda_handler.mjs:697:5)
    at async Runtime.handler (file:///var/task/lambda_handler.mjs:914:22)

I've tried a few different run throughs to make sure I didn't miss any steps.  Not sure why it is throwing the error

**Comment by jkendric** [comment]
Just refreshed the Pipedream workflow from your link and the code had changed - I had sorted it was an SDK that broke it. looks like you already fixed it.  Thanks!!!!
